# Generated by Django 4.0.4 on 2023-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0003_ripsprocedimiento_diagprocedimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambitoprocedimiento',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
