# Generated by Django 4.0.4 on 2023-07-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0004_ambitoprocedimiento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalidadprocedimiento',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambitoprocedimiento',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
