# Generated by Django 4.0.4 on 2023-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0005_finalidadprocedimiento_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinosalida',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadosalida',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formarealizactoqx',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalasistencial',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipomedicamento',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
