# Generated by Django 4.0.4 on 2023-07-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0006_destinosalida_codigo_estadosalida_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaingreso',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
