# Generated by Django 4.0.4 on 2023-07-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0008_ripsurgencia_diagripsurgencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsurgencia',
            name='diagmuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bai.diagnosticos'),
        ),
    ]
