# Generated by Django 4.0.4 on 2023-07-27 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0006_paciente_razonsocial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bai', '0009_alter_ripsurgencia_diagmuerte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ripsurgencia',
            options={'ordering': ['fechaingreso', 'paciente'], 'verbose_name_plural': 'Rips de Urgencia'},
        ),
        migrations.CreateModel(
            name='RipsHospitalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nrofactura', models.CharField(max_length=20)),
                ('fechaingreso', models.DateField()),
                ('horaingreo', models.TimeField()),
                ('nroautoriza', models.CharField(blank=True, max_length=15, null=True)),
                ('fechasalida', models.DateField()),
                ('horasalida', models.TimeField()),
                ('ViaIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.viaingreso')),
                ('causaexterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.causaexterna')),
                ('diagcomplicaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dxcomplicacion', to='bai.diagnosticos')),
                ('diagmuerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dxmuerte', to='bai.diagnosticos')),
                ('diagppalingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dxingreso', to='bai.diagnosticos')),
                ('estadosalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bai.estadosalida')),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.ips')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('ripscontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.ripscontrol')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Rips de Urgencia',
                'ordering': ['fechaingreso', 'paciente'],
            },
        ),
        migrations.CreateModel(
            name='DiagRipsHospitaliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('diagppal', models.CharField(blank=True, choices=[('SI', 'Diagnóstico principal'), ('NO', 'Diagnostico relacionado')], default='NO', max_length=2, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.diagnosticos')),
                ('ripshospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.ripshospitalizacion')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Diagnostico Egreso hospitalizacion',
                'ordering': ['diagppal', 'diagnostico'],
            },
        ),
    ]
