# Generated by Django 4.0.4 on 2023-07-28 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0006_paciente_razonsocial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bai', '0011_rename_viaingreso_ripshospitalizacion_viaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarcie10',
            name='file_cums',
            field=models.FileField(blank=True, null=True, upload_to='bai'),
        ),
        migrations.CreateModel(
            name='RipsMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nrofactura', models.CharField(max_length=20)),
                ('nroautoriza', models.CharField(blank=True, max_length=15, null=True)),
                ('nombregenerico', models.CharField(max_length=300)),
                ('formafarmaceutica', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=80)),
                ('unidadmedida', models.CharField(max_length=50)),
                ('numerodeunidades', models.FloatField(default=1)),
                ('valorunitario', models.FloatField(default=0)),
                ('valortotal', models.FloatField(default=0)),
                ('cums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.cums')),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.ips')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('ripscontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.ripscontrol')),
                ('tipomedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bai.tipomedicamento')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name_plural': 'Rips de Medicamentos',
                'ordering': ['nrofactura', 'paciente'],
            },
        ),
    ]
