# Generated by Django 4.0.4 on 2023-07-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bai', '0012_importarcie10_file_cums_ripsmedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripstransaccion',
            name='ripscontrol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bai.ripscontrol'),
            preserve_default=False,
        ),
    ]
