# Generated by Django 4.0.4 on 2022-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etnia',
            name='codigo',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
