# Generated by Django 4.0.4 on 2022-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0003_varbarrio_caractbarrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='lat',
            field=models.CharField(blank=True, default='SD', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='barrio',
            name='lon',
            field=models.CharField(blank=True, default='SD', max_length=20, null=True),
        ),
    ]
