# Generated by Django 4.0.4 on 2023-06-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0005_alter_paciente_apellido1_alter_paciente_apellido2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='razonsocial',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
