# Generated by Django 4.0.4 on 2023-08-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0006_paciente_razonsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.pais'),
        ),
        migrations.AddField(
            model_name='pais',
            name='nacional',
            field=models.BooleanField(default=False),
        ),
    ]
