# Generated by Django 4.2.7 on 2023-12-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0008_mes_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fechaNac',
            new_name='fechanac',
        ),
    ]
