# Generated by Django 4.2.7 on 2024-01-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0010_tipoafiliado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoAfiliado',
        ),
    ]
