# Generated by Django 4.2.7 on 2024-01-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0011_delete_tipoafiliado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodoc',
            options={'ordering': ['descripcion'], 'verbose_name_plural': 'Tipos de documentos'},
        ),
    ]
