# Generated by Django 4.0.4 on 2022-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rediario',
            name='reportado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
