# Generated by Django 4.0.4 on 2023-08-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0007_paciente_pais_pais_nacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pai', '0002_rediario_reportado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=80)),
                ('usadiluyente', models.BooleanField(default=False)),
                ('usajeringa', models.BooleanField(default=True)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dosisbiologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=80)),
                ('biologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pai.biologico')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jeringas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rediarioregular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('edadanios', models.IntegerField(default=0)),
                ('edadmes', models.IntegerField(default=0)),
                ('edaddias', models.IntegerField(default=0)),
                ('edadtotalmeses', models.IntegerField(default=0)),
                ('desplazado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('discapacitado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('fallecido', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('victima', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('estudiante', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('autorizallamada', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('autorizaenvemail', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('loteBiologico', models.CharField(max_length=20)),
                ('lotejeringa', models.CharField(blank=True, max_length=20, null=True)),
                ('lotediluyente', models.CharField(blank=True, max_length=20, null=True)),
                ('biologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pai.biologico')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_cuidador', to='cnf.paciente')),
                ('dosisbiologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pai.dosisbiologico')),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.ips')),
                ('jeringa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pai.jeringas')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_madre', to='cnf.paciente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_paciente', to='cnf.paciente')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
