# Generated by Django 4.0.4 on 2023-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pai', '0003_biologico_dosisbiologico_jeringas_rediarioregular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologico',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
