# Generated by Django 4.0.4 on 2023-08-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pai', '0004_alter_biologico_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rediarioregular',
            name='namevacunador',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rediarioregular',
            name='nrofrascos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rediarioregular',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rediarioregular',
            name='registroenpaiweb',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True),
        ),
    ]
