# Generated by Django 4.0.4 on 2023-09-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0007_paciente_pais_pais_nacional'),
        ('pai', '0006_rediariopairegcargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rediarioregular',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dato_cuidador', to='cnf.paciente'),
        ),
        migrations.AlterField(
            model_name='rediarioregular',
            name='dosisbiologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pai.dosisbiologico'),
        ),
        migrations.AlterField(
            model_name='rediarioregular',
            name='loteBiologico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rediarioregular',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dato_madre', to='cnf.paciente'),
        ),
    ]
