# Generated by Django 4.0.4 on 2023-09-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0008_mes_periodo'),
        ('pai', '0007_alter_rediarioregular_cuidador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rediariopairegcargado',
            options={'verbose_name': 'Import rediario PAI Regular'},
        ),
        migrations.AddField(
            model_name='rediariopairegcargado',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cnf.periodo'),
            preserve_default=False,
        ),
    ]
