# Generated by Django 4.0.4 on 2023-09-30 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pai', '0008_alter_rediariopairegcargado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rediarioregular',
            name='biologico',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='dosisbiologico',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='jeringa',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='loteBiologico',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='lotediluyente',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='lotejeringa',
        ),
        migrations.RemoveField(
            model_name='rediarioregular',
            name='nrofrascos',
        ),
        migrations.CreateModel(
            name='RediarioRegBiologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nrofrascos', models.IntegerField(blank=True, default=0, null=True)),
                ('loteBiologico', models.CharField(blank=True, max_length=20, null=True)),
                ('lotejeringa', models.CharField(blank=True, max_length=20, null=True)),
                ('lotediluyente', models.CharField(blank=True, max_length=20, null=True)),
                ('biologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pai.biologico')),
                ('dosisbiologico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pai.dosisbiologico')),
                ('jeringa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pai.jeringas')),
                ('rediarioregular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pai.rediarioregular')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
