# Generated by Django 4.0.4 on 2022-05-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0003_alter_maestrosub_nivelsisben_condiciondiscapacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestrosub',
            name='tipopoblacionesp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipopoblacionesp'),
        ),
    ]
