# Generated by Django 4.0.4 on 2022-05-25 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0002_etnia_codigo'),
        ('aseg', '0004_alter_maestrosub_tipopoblacionesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocontizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo de cotizante',
            },
        ),
        migrations.CreateModel(
            name='Tipoafiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo de Afiliado',
            },
        ),
        migrations.CreateModel(
            name='Maestrocont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('identcotizante', models.CharField(blank=True, max_length=20, null=True)),
                ('identificacion', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=60)),
                ('apellido2', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre1', models.CharField(max_length=60)),
                ('nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanac', models.DateField()),
                ('fechaafiliacion', models.DateField()),
                ('identaportante', models.CharField(blank=True, max_length=20, null=True)),
                ('razonsocial', models.CharField(max_length=250)),
                ('Tipoafiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipoafiliado')),
                ('actividadeconomica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.actividadeconomica')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.area')),
                ('condiciondiscapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.condiciondiscapacidad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.departamento')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.eps')),
                ('ipsodontologica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ipsodontologica', to='cnf.ips')),
                ('ipsprimaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ipsprimaria', to='cnf.ips')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
                ('parentezcocf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.parentezcocf')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.sexo')),
                ('tipocotizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipocontizante')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipodocumento', to='cnf.tipodoc')),
                ('tipodocaportante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipodoc_aporta', to='cnf.tipodoc')),
                ('tipodoccotizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipodoc_cotiza', to='cnf.tipodoc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Maestro Contributivo',
            },
        ),
    ]
