# Generated by Django 4.0.4 on 2022-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0005_tipocontizante_tipoafiliado_maestrocont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestrocont',
            old_name='Tipoafiliado',
            new_name='tipoafiliado',
        ),
        migrations.AddField(
            model_name='maestrocont',
            name='estadoactual',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
