# Generated by Django 4.2.7 on 2023-12-20 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0010_tipoafiliado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0006_rename_tipoafiliado_maestrocont_tipoafiliado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formularioafil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fechafiliacion', models.DateField()),
                ('aprobar', models.CharField(choices=[('A', 'Aprobar'), ('D', 'Desaprobar'), ('X', 'Sin Evaluar')], max_length=1)),
                ('opcdesaprueba', models.CharField(blank=True, choices=[('NS', 'No Sensado'), ('RO', 'Reside en otro municipio'), ('SO', 'Sensado en otro municipio'), ('OT', 'Otros')], max_length=2, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('TipoAfiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipoafiliado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Formularios de Afiliación',
                'ordering': ['-fechafiliacion'],
            },
        ),
    ]
