# Generated by Django 4.2.7 on 2024-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0008_novedadbdua_repnovedad_causalretiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalretiro',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='novedadbdua',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
