# Generated by Django 4.2.7 on 2024-01-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0010_rename_tipoafiliado_formularioafil_tipoafiliado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioafil',
            name='tipoafiliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipoafiliado'),
        ),
    ]
