# Generated by Django 4.2.7 on 2024-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0011_alter_formularioafil_tipoafiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioafil',
            name='aprobar',
            field=models.CharField(choices=[('A', 'Aprobar'), ('D', 'Desaprobar'), ('X', 'Sin Evaluar')], default='X', max_length=1),
        ),
    ]
