# Generated by Django 4.2.7 on 2024-01-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0011_delete_tipoafiliado'),
        ('aseg', '0013_tiporeportesat_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sat',
            name='epsdest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eps_destino', to='cnf.eps'),
        ),
        migrations.AlterField(
            model_name='sat',
            name='fechanovedad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
