# Generated by Django 4.2.7 on 2024-01-15 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0011_delete_tipoafiliado'),
        ('aseg', '0016_alter_listadocensal_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribSolidaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fechaingreso', models.DateField()),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('fechaliquidacion', models.DateField()),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('RE', 'Retirado')], default='AC', max_length=2)),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('atendido', models.BooleanField(blank=True, default=False, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps', to='cnf.eps')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimen', to='cnf.regimen')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Contribución solidaria',
            },
        ),
    ]
