# Generated by Django 4.2.7 on 2024-01-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0019_modalidad_poblacionespsinls'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIAseguramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cuentaconsi', models.BooleanField(default=True)),
                ('realizacruces', models.BooleanField(default=True)),
                ('bdcruces', models.CharField(blank=True, max_length=80, null=True)),
                ('herramientasw', models.CharField(blank=True, max_length=80, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Sistema de información utilizado',
            },
        ),
    ]
