# Generated by Django 4.2.7 on 2024-01-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0020_siaseguramiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descactividad', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('timpodedicado', models.IntegerField(default=1)),
                ('indicador', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Plan de cobertura',
            },
        ),
    ]
