# Generated by Django 4.2.7 on 2024-01-17 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0011_delete_tipoafiliado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0022_afiloficiosinsisben'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfilSubGrupo5SinSisben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('usuarioencuestado', models.BooleanField(default=False)),
                ('fechaencuesta', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.area')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.departamento')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.eps')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.modalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('tipopoblacionesp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipopoblacionesp')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Afiliado subsidiado grupo 5 sin encuesta sisben IV',
            },
        ),
    ]
