# Generated by Django 4.2.7 on 2024-01-17 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0011_delete_tipoafiliado'),
        ('aseg', '0023_afilsubgrupo5sinsisben'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSisbenIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Grupo categoria sisben IV',
                'verbose_name_plural': 'Grupos categorias sisben IV',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SubgrupoSisbenIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('gruposisbeniv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aseg.gruposisbeniv')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Sub grupo categoria sisben IV',
                'verbose_name_plural': 'Sub grupos categorias sisben IV',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Movilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nivelsisbenpe', models.CharField(blank=True, max_length=80, null=True)),
                ('nrofuasat', models.CharField(blank=True, max_length=80, null=True)),
                ('usuarioregsat', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpto_movilidad', to='cnf.departamento')),
                ('departamentosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpto_movilidad_sisben', to='cnf.departamento')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.eps')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpio_movilidad', to='cnf.municipio')),
                ('municipiosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpio_movilidad_sisben', to='cnf.municipio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.regimen')),
                ('subgruposisbeniv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.subgruposisbeniv')),
                ('tipoafiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipoafiliado')),
                ('tipopoblacionesp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipopoblacionesp')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Afiliado subsidiado grupo 5 sin encuesta sisben IV',
            },
        ),
    ]
