# Generated by Django 4.2.7 on 2024-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0024_gruposisbeniv_subgruposisbeniv_movilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movilidad',
            name='fechaefectivamov',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movilidad',
            name='fechasolicitud',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
