# Generated by Django 4.2.7 on 2024-01-18 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0011_delete_tipoafiliado'),
        ('aseg', '0025_movilidad_fechaefectivamov_movilidad_fechasolicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movilidad',
            options={'verbose_name': 'Movilidad'},
        ),
        migrations.CreateModel(
            name='Portabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fechasolicitud', models.DateField()),
                ('fechaaplicacion', models.DateField(blank=True, null=True)),
                ('fechaatenciojn', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('RE', 'Retirado'), ('SU', 'Suspendido')], default='AC', max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpto_portabilidad', to='cnf.departamento')),
                ('departamentodest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpto_portabilidad_destino', to='cnf.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpio_portabilidad', to='cnf.municipio')),
                ('municipiodest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpio_portabilidad_destino', to='cnf.municipio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Portabilidad',
            },
        ),
    ]
