# Generated by Django 4.2.7 on 2024-01-18 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cnf', '0012_alter_tipodoc_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aseg', '0029_portabilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausActDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Modalidad de aseguramiento',
                'verbose_name_plural': 'Modalidades de aseguramientos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='NovLcRegTipo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('tiporegistro', models.IntegerField(default=1)),
                ('tipoentidad', models.CharField(choices=[('MU', 'Municipio'), ('DE', 'Departamento'), ('DI', 'Distrito')], default='MU', max_length=2)),
                ('nroidententidad', models.CharField(max_length=20)),
                ('fechafinal', models.DateField()),
                ('nrototalreg', models.IntegerField(default=0)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Novedad listados censal registro tipo 1',
            },
        ),
        migrations.CreateModel(
            name='NovLcRegTipo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('tiporegistro', models.IntegerField(default=2)),
                ('identificacion', models.CharField(max_length=16)),
                ('identificacionnew', models.CharField(max_length=16)),
                ('fechaaplicanovedad', models.DateField()),
                ('NovLcRegTipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aseg.novlcregtipo1')),
                ('causactdocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aseg.causactdocumento')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdnovlc2', to='cnf.tipodoc')),
                ('tipodocnew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdnovlc2new', to='cnf.tipodoc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Detalle novedad listado censal registro tipo 2',
            },
        ),
    ]
