# Generated by Django 4.2.7 on 2024-01-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0030_causactdocumento_novlcregtipo1_novlcregtipo2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causactdocumento',
            options={'ordering': ['descripcion'], 'verbose_name': 'Causa de actualización de documentos', 'verbose_name_plural': 'Causales de actualización de documentos'},
        ),
        migrations.RenameField(
            model_name='novlcregtipo2',
            old_name='NovLcRegTipo1',
            new_name='novlcregtipo1',
        ),
    ]
