# Generated by Django 4.2.7 on 2024-01-18 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0012_alter_tipodoc_options'),
        ('aseg', '0033_novlcregtipo4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novlcregtipo4',
            name='tiporegistro',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='NovLcRegTipo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('tiporegistro', models.IntegerField(default=5)),
                ('identificacion', models.CharField(max_length=16)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
                ('novlcregtipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aseg.novlcregtipo1')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdnovlc5', to='cnf.tipodoc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Detalle novedad listado censal registro tipo 5 Municipio',
            },
        ),
    ]
