# Generated by Django 4.2.7 on 2024-01-19 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0012_alter_tipodoc_options'),
        ('aseg', '0043_novlcregtipo12'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo de traslado',
                'verbose_name_plural': 'Tipos de traslados',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='NovedadS1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=60)),
                ('apellido2', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre1', models.CharField(max_length=60)),
                ('nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanac', models.DateField()),
                ('identificacionact', models.CharField(max_length=20)),
                ('apellido1act', models.CharField(max_length=60)),
                ('apellido2act', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre1act', models.CharField(max_length=60)),
                ('nombre2act', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacact', models.DateField()),
                ('fechafilnov', models.DateField()),
                ('condiscapacidad', models.CharField(blank=True, max_length=1, null=True)),
                ('identificacioncabfam', models.CharField(blank=True, max_length=20, null=True)),
                ('tiponovedad', models.CharField(blank=True, choices=[('VAL', 'VALIDADAS'), ('NEG', 'NEGADAS')], default='NEG', max_length=3, null=True)),
                ('descglosa', models.TextField(blank=True, null=True)),
                ('acciones', models.TextField(blank=True, null=True)),
                ('TipoTraslado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipotraslado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.area')),
                ('condiciondiscapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.condiciondiscapacidad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.departamento')),
                ('epsrecibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epsrecibe', to='cnf.eps')),
                ('epssol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novs1epsol', to='cnf.eps')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnf.etnia')),
                ('metodologiagp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.metodologiagp')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.municipio')),
                ('nivelsisben', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.nivelsisben')),
                ('parentezcocf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.parentezcocf')),
                ('resguardo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.resguardo')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novs1sex', to='cnf.sexo')),
                ('sexoact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novs1sexact', to='cnf.sexo')),
                ('subgruposisbeniv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.subgruposisbeniv')),
                ('tipoafiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipoafiliado')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpdocbduas1', to='cnf.tipodoc')),
                ('tipodocabfam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipodocabfams1', to='cnf.tipodoc')),
                ('tipodocact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpdocacts1', to='cnf.tipodoc')),
                ('tipopoblacionesp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseg.tipopoblacionesp')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Novedad S1',
            },
        ),
    ]
