# Generated by Django 4.2.7 on 2024-01-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aseg', '0044_tipotraslado_novedads1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedads1',
            old_name='TipoTraslado',
            new_name='tipotraslado',
        ),
    ]
