# Generated by Django 4.2.7 on 2024-01-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='Serviciosobjqueja',
            new_name='serviciosobjqueja',
        ),
    ]
