# Generated by Django 4.2.7 on 2024-01-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_rename_serviciosobjqueja_pqrs_serviciosobjqueja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='victima',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
    ]
