# Generated by Django 4.0.4 on 2022-04-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Tipo de Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='RepLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fechamuestra', models.DateField()),
                ('resultado', models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEG', 'Negativo')], max_length=3, null=True)),
                ('fecharesultado', models.DateField(blank=True, null=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.muestra')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('redlaboratorios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.redlaboratorios')),
                ('tipoexamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.tipoexamen')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario automatio')),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modifica')),
            ],
            options={
                'verbose_name': 'Reporte de Laboratorios',
                'ordering': ['fechamuestra'],
            },
        ),
    ]
