# Generated by Django 4.2.7 on 2024-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnotifcovid',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='segnotifcovid',
            name='fecproxseg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
