# Generated by Django 4.0.4 on 2022-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0004_actaestabeducativo_aislamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atiende_actaestabeduc',
            name='nombre',
            field=models.CharField(default='_', max_length=100),
            preserve_default=False,
        ),
    ]
