# Generated by Django 4.0.4 on 2022-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0005_atiende_actaestabeduc_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemactaestabeducativo',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
