# Generated by Django 4.0.4 on 2022-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0006_bloque_orden_itemactaestabeducativo_habilitada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.FloatField(default=0),
        ),
    ]
