# Generated by Django 4.0.4 on 2022-09-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0007_alter_pregunta_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden'], 'verbose_name': 'Variables a Evaluar'},
        ),
    ]
