# Generated by Django 4.0.4 on 2022-04-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSintomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Sintomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('fiebre', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('cefalea', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('doloretrocular', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('mialgias', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('artralgias', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('rash', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('zona_endemica_dengue', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('tos', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('perdida_peso', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('sudor_nocturna', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnf.paciente')),
                ('tiposintomatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sint.tiposintomatico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
